function [response_characteristics]=FF_Aggregate_Analyses_TwoSource(stimRootDir, controlRootDir)
% [fitCharacteristics]=FF_Aggregate_Analyses_TwoSource(stimRootDir, controlRootDir)
%
%   Calculates pooled variance across a set of pre-analyzed 
%   signals from stimulus and control trials, performs the subtraction
%   between their standard deviations, and performs a piecewise fit of the 
%   resulting subtraction.
%
%   This script is designed to work with FULL FIELD datasets- that is, each
%   dataset (mat file) contains *only* control or stimulus data.
%
%   Normally, the user doesn't need to select a stimulus or control root
%   directory (that will be found automatically by
%   "FF_Aggregate_Multi_Trial_Run.m"), but if the software is run by
%   itself it will prompt the user for the folders containing the
%   pre-analyzed mat files generated by Rel_FF_Temporal_Reflectivity_Analysis.m.
%
% Inputs:
%       stimRootDir: The folder path of the pre-analyzed (.mat) stimulus
%       trials. Each mat file must contain valid stimulus signals.
%
%       controlRootDir: The folder path of the pre-analyzed (.mat) control
%       trials. Each mat file must contain valid control signals.
%
% Outputs:
%       fitCharacteristics: Information extracted from the mat files and
%       the fitted subtracted signal.
%
% Created by Robert F Cooper 06-20-2017
%
% The analyses performed in this script are from Cooper et al. "Non-invasive 
% assessment of human cone photoreceptor function", and
% encompassed in Figures 4B/5A, Equation 3.


if ~exist('stimRootDir','var')
    close all force;
    stimRootDir = uigetdir(pwd, 'Select the directory containing the stimulus profiles');
    controlRootDir = uigetdir(pwd, 'Select the directory containing the control profiles');
end

profileSDataNames = read_folder_contents(stimRootDir,'mat');
profileCDataNames = read_folder_contents(controlRootDir,'mat');

thatstimmax=0;
thatcontrolmax=0;
%% Code for determining variance across all signals at given timepoint

allmax = 400;
num_control_cones = 0;
num_stim_cones = 0;
max_cones = 0;
min_cones = 10000000000000;
mean_control_reflectance = zeros(500,1);
num_contributors_control_reflectance = zeros(500,1);

for j=1:length(profileCDataNames)

    profileCDataNames{j}
    load(fullfile(controlRootDir,profileCDataNames{j}));
    
    % Remove empty cells
    norm_control_cell_reflectance = norm_cell_reflectance( ~cellfun(@isempty,norm_cell_reflectance)  );
    control_cell_times            = cell_times( ~cellfun(@isempty,cell_times) );

    
    num_control_cones = num_control_cones+length(control_cell_times);
    
    thatcontrolmax = max( cellfun(@max,control_cell_times) );

    % Pooled variance of all cells before first stimulus
    [ ref_variance_control{j},ref_control_times{j}, ref_control_count{j} ] = reflectance_pooled_variance( control_cell_times, norm_control_cell_reflectance, allmax );    


    i=1;
    while i<= length( ref_control_times{j} )

        % Remove times from both stim and control that are NaN, or 0
        if  isnan(ref_control_times{j}(i)) || ref_control_times{j}(i) ==0 || isnan(ref_variance_control{j}(i)) || ref_variance_control{j}(i) ==0

            ref_control_count{j}(i) = [];
            ref_control_times{j}(i) = [];
            ref_variance_control{j}(i) = [];        
        else
            i = i+1;
        end

    end
    precontrol = ref_variance_control{j}(ref_control_times{j}<=66)./ref_control_count{j}(ref_control_times{j}<=66);
    figure(8); plot(ref_control_times{j}/16.6, sqrt(ref_variance_control{j}./ref_control_count{j})-sqrt(mean(precontrol)) ); hold on; drawnow;      
%     pause;
end

%%
hold off;axis([0 16 0 6])

for j=1:length(profileSDataNames)

    profileSDataNames{j}
    load(fullfile(stimRootDir,profileSDataNames{j}));
    
    % Remove the empty cells
    norm_stim_cell_reflectance = norm_cell_reflectance( ~cellfun(@isempty,norm_cell_reflectance) );
    stim_cell_times            = cell_times(  ~cellfun(@isempty,cell_times) );

    num_stim_cones = num_stim_cones+length(stim_cell_times);
    
    thatstimmax = max( cellfun(@max,stim_cell_times) );    
    
    % Pooled variance of all cells before first stimulus
    [ ref_variance_stim{j}, ref_stim_times{j}, ref_stim_count{j} ] = reflectance_pooled_variance( stim_cell_times, norm_stim_cell_reflectance, allmax );

    i=1;
    while i<= length( ref_stim_times{j} )

        % Remove times from both stim and control that are NaN, or 0
        if isnan(ref_stim_times{j}(i)) || ref_stim_times{j}(i) == 0 || isnan(ref_variance_stim{j}(i)) || ref_variance_stim{j}(i) == 0

            ref_stim_count{j}(i) = [];
            
            ref_stim_times{j}(i) = [];

            ref_variance_stim{j}(i) = [];
      
        else
            i = i+1;
        end

    end
    
    prestim = ref_variance_stim{j}(ref_stim_times{j}<=66)./ref_stim_count{j}(ref_stim_times{j}<=66);
    figure(9); plot(ref_stim_times{j}/16.6, sqrt( ref_variance_stim{j}./ref_stim_count{j})-sqrt(mean(prestim)) ); hold on; drawnow;

end
hold off;axis([0 16 0 6])

% if (length(stim_cell_times) + length(control_cell_times)) < min_cones
%     min_cones = (length(stim_cell_times) + length(control_cell_times));
% end
% if (length(stim_cell_times) + length(control_cell_times)) > max_cones
%     max_cones = (length(stim_cell_times) + length(control_cell_times));
% end
%%
pooled_variance_stim = zeros(allmax,1);
pooled_variance_stim_count = zeros(allmax,1);
all_variance_stim = nan(length(profileSDataNames),allmax);

pooled_variance_control = zeros(allmax,1);
pooled_variance_control_count = zeros(allmax,1);
all_variance_control = nan(length(profileCDataNames), allmax);

% Create the pooled variance for each of these

for j=1:length(profileSDataNames)    
    for i=1:length(ref_stim_times{j})
    
        % Create the upper and lower halves of our pooled variance
        pooled_variance_stim( ref_stim_times{j}(i) ) = pooled_variance_stim( ref_stim_times{j}(i) ) + ref_variance_stim{j}(i);
        pooled_variance_stim_count( ref_stim_times{j}(i) ) = pooled_variance_stim_count( ref_stim_times{j}(i) ) + (ref_stim_count{j}(i)-1);
        
    end
    all_variance_stim(j, ref_stim_times{j}) = ref_variance_stim{j}./(ref_stim_count{j}-1);
end

for j=1:length(profileCDataNames) 
    for i=1:length(ref_control_times{j})
    
        % Create the upper and lower halves of our pooled variance
        pooled_variance_control( ref_control_times{j}(i) ) = pooled_variance_control( ref_control_times{j}(i) ) + ref_variance_control{j}(i);
        pooled_variance_control_count( ref_control_times{j}(i) ) = pooled_variance_control_count( ref_control_times{j}(i) ) + (ref_control_count{j}(i)-1);

    end
    all_variance_control(j, ref_control_times{j}) = ref_variance_control{j}./(ref_control_count{j}-1);
end
%%
for i=1:length(pooled_variance_stim)    
    pooled_variance_stim(i) = pooled_variance_stim(i)/pooled_variance_stim_count(i);
end
for i=1:length(pooled_variance_control)    
    pooled_variance_control(i) = pooled_variance_control(i)/pooled_variance_control_count(i);
end
%% Output
% For structure: /stuff/id/intensity/time/data
[remain kid] = getparent(stimRootDir);

% [remain region] = getparent(remain);
[remain stim_loc] = getparent(remain);
[remain stim_intensity] = getparent(remain);
[remain stim_time] = getparent(remain);
[remain stimwave] = getparent(remain);
[~, id] = getparent(remain);

outFname = [id '_' stimwave '_' stim_intensity '_' stim_time  '_' stim_loc '_aggregate_' num2str(length(profileSDataNames)) '_signals_twosource'];

figure(8);  title('All control signals'); xlabel('Frame #'); ylabel('Standard deviations'); %axis([0 249 -20 75]);
saveas(gcf, fullfile(pwd, [outFname '_allcontrol.png']), 'png' );
figure(9);  title('All stimulus signals'); xlabel('Frame #'); ylabel('Standard deviations'); %axis([0 249 -20 75]);
saveas(gcf, fullfile(pwd, [outFname '_allstim.png']), 'png' );

hz=17.75;
stim_start = 72;
timeBase = ((1:allmax)/hz)';

dlmwrite(fullfile(pwd, [outFname '.csv']), [timeBase sqrt(pooled_variance_stim) sqrt(pooled_variance_control)], ',' );


figure(10); 
plot( timeBase,sqrt(pooled_variance_stim)-1,'r'); hold on;
plot( timeBase,sqrt(pooled_variance_control)-1,'b');


pooled_std_stim    = sqrt(pooled_variance_stim)-sqrt(pooled_variance_control);
plot( timeBase(~isnan(pooled_std_stim)), pooled_std_stim(~isnan(pooled_std_stim)),'k'); hold on;
legend('Stimulus cones','Control cones','Subtraction');


% Stim train
stimlen = str2double( strrep(stim_time(1:3),'p','.') );

trainlocs = stim_start/hz:1/hz:(stim_start/hz+stimlen);
plot(trainlocs, max(pooled_std_stim)*ones(size(trainlocs)),'r*'); hold off;

% plot(stim_locs, max([ref_variance_stim; ref_variance_control])*ones(size(stim_locs)),'r*'); hold off;
ylabel('Pooled Standard deviation'); xlabel('Time (s)'); title( [stim_intensity ' ' stim_time 'pooled standard deviation of ' num2str(length(profileSDataNames)) ' signals.'] );
axis([0 16 -1 5])
hold off;
saveas(gcf, fullfile(pwd, [outFname '.png']), 'png' );
% saveas(gcf, fullfile(pwd, [outFname '.svg']), 'svg' );

save( fullfile(pwd,['pooled_var_aggregate_' num2str(length(profileSDataNames)) '_signals.mat' ] ),...
        'pooled_std_stim','pooled_variance_control', 'timeBase','profileSDataNames', 'stimRootDir','allmax');

disp('Done.');
% dlmwrite(fullfile(pwd, [date '_all_plots.csv']), [ [str2double(id(4:end)), str2double(stim_intensity(1:3)), stimlen] ;[ timeBase sqrt(pooled_variance_stim) sqrt(pooled_variance_control) ] ]',...
%          '-append', 'delimiter', ',', 'roffset',1);


